# Generated by Django 4.0.3 on 2023-02-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0003_user_result_his'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=3)),
                ('login_id', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
